export type SourceTrustLevel = 'high' | 'medium' | 'low' | 'unknown';

export interface SourceTrustInfo {
  label: string;
  trust: SourceTrustLevel;
  description: string;
  dotColor: string;
  textColor: string;
}

const TRUST_MAP: Record<string, SourceTrustInfo> = {
  user_gloss: {
    label: 'Your Gloss',
    trust: 'high',
    description: 'Your custom translation',
    dotColor: '#10B981',
    textColor: 'text-green-700',
  },
  static_compact: {
    label: 'Dictionary',
    trust: 'high',
    description: 'Static dictionary entry',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  corpus_derived: {
    label: 'Dictionary',
    trust: 'high',
    description: 'Curated dictionary entry from the corpus',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  static_dictionary: {
    label: 'Dictionary',
    trust: 'high',
    description: 'Entry from a reference lexicon (Strong\'s, LSJ, etc.)',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  corpus_global: {
    label: 'Corpus',
    trust: 'medium',
    description: 'Gloss derived from corpus-wide annotations',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  token_gloss: {
    label: 'Token gloss',
    trust: 'medium',
    description: 'Gloss embedded in the text token data',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  ai_explanation: {
    label: 'AI Suggestion',
    trust: 'low',
    description: 'Generated by AI — verify before relying on it',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  wiktionary: {
    label: 'Wiktionary',
    trust: 'medium',
    description: 'Community-contributed dictionary (CC BY-SA)',
    dotColor: '#8B5CF6',
    textColor: 'text-purple-700',
  },
  'logeion-lsj': {
    label: 'LSJ',
    trust: 'high',
    description: 'Liddell-Scott-Jones Greek-English Lexicon (Public Domain)',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  'logeion-middleLiddell': {
    label: 'Middle Liddell',
    trust: 'high',
    description: 'An Intermediate Greek-English Lexicon (Public Domain)',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  'logeion-ls': {
    label: 'Lewis & Short',
    trust: 'high',
    description: "Lewis & Short Latin Dictionary (Public Domain)",
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  'logeion-logeion': {
    label: 'Logeion',
    trust: 'high',
    description: 'Logeion Greek/Latin lexicon (University of Chicago)',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  'sefaria-bdb': {
    label: 'BDB',
    trust: 'high',
    description: 'Brown-Driver-Briggs Hebrew-English Lexicon via Sefaria',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  ai_fallback: {
    label: 'AI Suggestion',
    trust: 'low',
    description: 'Generated by AI — verify before relying on it',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  ai_cached: {
    label: 'AI cached',
    trust: 'low',
    description: 'Cached AI suggestion — verify before relying on it',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  metadata: {
    label: 'Token metadata',
    trust: 'low',
    description: 'Derived from token metadata — not a true definition',
    dotColor: '#9CA3AF',
    textColor: 'text-gray-500',
  },
  unavailable: {
    label: 'Unavailable',
    trust: 'unknown',
    description: 'No definition could be determined',
    dotColor: '#9CA3AF',
    textColor: 'text-gray-400',
  },
};

export function getSourceTrust(source: string): SourceTrustInfo {
  return TRUST_MAP[source] ?? {
    label: 'Unknown',
    trust: 'unknown' as SourceTrustLevel,
    description: 'Source could not be determined',
    dotColor: '#9CA3AF',
    textColor: 'text-gray-400',
  };
}
