export type SourceTrustLevel = 'high' | 'medium' | 'low' | 'unknown';

export interface SourceTrustInfo {
  label: string;
  trust: SourceTrustLevel;
  description: string;
  dotColor: string;
  textColor: string;
}

const TRUST_MAP: Record<string, SourceTrustInfo> = {
  user_gloss: {
    label: 'Your Gloss',
    trust: 'high',
    description: 'Your custom translation',
    dotColor: '#10B981',
    textColor: 'text-green-700',
  },
  corpus_derived: {
    label: 'Dictionary',
    trust: 'high',
    description: 'Curated dictionary entry from the corpus',
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  static_dictionary: {
    label: 'Dictionary',
    trust: 'high',
    description: "Entry from a reference lexicon (Strong's, LSJ, etc.)",
    dotColor: '#3B82F6',
    textColor: 'text-blue-700',
  },
  corpus_global: {
    label: 'Corpus',
    trust: 'medium',
    description: 'Gloss derived from corpus-wide annotations',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  token_gloss: {
    label: 'Token gloss',
    trust: 'medium',
    description: 'Gloss embedded in the text token data',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  ai_explanation: {
    label: 'AI Suggestion',
    trust: 'low',
    description: 'Generated by AI — verify before relying on it',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  wiktionary: {
    label: 'Wiktionary',
    trust: 'medium',
    description: 'Community-contributed dictionary (CC BY-SA)',
    dotColor: '#8B5CF6',
    textColor: 'text-purple-700',
  },
  ai_fallback: {
    label: 'AI Suggestion',
    trust: 'low',
    description: 'Generated by AI — verify before relying on it',
    dotColor: '#D97706',
    textColor: 'text-amber-700',
  },
  metadata: {
    label: 'Token metadata',
    trust: 'low',
    description: 'Derived from token metadata — not a true definition',
    dotColor: '#9CA3AF',
    textColor: 'text-gray-500',
  },
  unavailable: {
    label: 'Unavailable',
    trust: 'unknown',
    description: 'No definition could be determined',
    dotColor: '#9CA3AF',
    textColor: 'text-gray-400',
  },
};

export function getSourceTrust(source: string): SourceTrustInfo {
  return (
    TRUST_MAP[source] ?? {
      label: 'Unknown',
      trust: 'unknown' as SourceTrustLevel,
      description: 'Source could not be determined',
      dotColor: '#9CA3AF',
      textColor: 'text-gray-400',
    }
  );
}
