/**
 * Local (file-served) corpus — full texts completed by the ingestion pipeline
 * and committed as JSON under `api/_data/corpus/`, served by `api/_routes/corpus.ts`.
 *
 * This is the third corpus source, alongside the static bundle and Firestore.
 * It exists so full works (whole Bible books, …) can be COMPLETED and served in
 * the app WITHOUT either (a) bloating the single eager `corpus` JS chunk that
 * every visitor downloads, or (b) requiring Firestore credentials. The JSON is
 * read on the server, on demand, and reaches the Reader through the same
 * `/api/corpus/*` endpoints the Firestore path uses — so no client change is
 * needed (the Reader treats any non-static text as remote and fetches sections).
 *
 * Each file is one `{ text, sections }` record (the pipeline's `IngestedText`
 * shape). Generated by `scripts/corpus/ingest/run-manifest.ts --emit-local`.
 */
import { readdirSync, readFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import type { Text, TextSection } from '../../src/types/corpus.js';

interface LocalCorpusRecord {
  text: Text;
  sections: TextSection[];
}

// Resolve relative to this file so the path is correct both in dev (tsx) and in
// a bundled serverless function. Deployments must include api/_data/** (see
// vercel.json includeFiles).
const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '_data', 'corpus');

let _cache: Map<string, LocalCorpusRecord> | null = null;

function load(): Map<string, LocalCorpusRecord> {
  if (_cache) return _cache;
  const map = new Map<string, LocalCorpusRecord>();
  try {
    if (existsSync(DATA_DIR)) {
      for (const file of readdirSync(DATA_DIR)) {
        if (!file.endsWith('.json')) continue;
        try {
          const rec = JSON.parse(readFileSync(join(DATA_DIR, file), 'utf-8')) as LocalCorpusRecord;
          if (rec?.text?.id) map.set(rec.text.id, rec);
        } catch {
          // skip a malformed file rather than failing the whole route
        }
      }
    }
  } catch {
    // directory unreadable — behave as if there is no local corpus
  }
  _cache = map;
  return map;
}

export interface LocalCorpusListItem {
  id: string;
  title: string;
  languageId: string;
  sourceStatus: string | undefined;
  isSample: boolean;
  sentenceCount: number;
  sectionsPreview: { id: string; label: string }[];
}

export function listLocalCorpus(lang?: string): LocalCorpusListItem[] {
  const out: LocalCorpusListItem[] = [];
  for (const { text } of load().values()) {
    const languageId = (text as any).languageId || text.language;
    if (lang && languageId !== lang) continue;
    out.push({
      id: text.id,
      title: text.title,
      languageId,
      sourceStatus: text.sourceStatus,
      isSample: text.isSample ?? false,
      sentenceCount: text.sentenceCount ?? 0,
      sectionsPreview: text.sectionsPreview ?? [],
    });
  }
  return out;
}

export function getLocalText(textId: string): Text | null {
  return load().get(textId)?.text ?? null;
}

export function getLocalSection(textId: string, sectionId: string): TextSection | null {
  const rec = load().get(textId);
  if (!rec) return null;
  return rec.sections.find((s) => s.id === sectionId) ?? null;
}

/** Test/maintenance hook: drop the in-memory cache so new files are picked up. */
export function _resetLocalCorpusCache(): void {
  _cache = null;
}
