import React, { useState, useEffect } from "react";
import { X, Sparkles, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { AIClient } from "../../lib/services/aiClient";
import { useAuth } from "../../lib/hooks/useAuth";

interface ParadigmModalProps {
  isOpen: boolean;
  onClose: () => void;
  lemma: string;
  languageId: string;
  word: string;
}

export const ParadigmModal: React.FC<ParadigmModalProps> = ({
  isOpen,
  onClose,
  lemma,
  languageId,
  word,
}) => {
  const { user } = useAuth();
  const [paradigm, setParadigm] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (isOpen && lemma) {
      const fetchParadigm = async () => {
        setIsLoading(true);
        try {
          const result = await AIClient.getParadigm(languageId, word, lemma, user?.uid);
          setParadigm(result);
        } catch (error: any) {
          console.error(error);
          setParadigm(error.message || "Failed to load paradigm data.");
        } finally {
          setIsLoading(false);
        }
      };
      fetchParadigm();
    }
  }, [isOpen, lemma, languageId, word, user?.uid]);

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-ink/40 backdrop-blur-sm"
          />
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 20 }}
            className="relative bg-parch2 w-full max-w-2xl max-h-[80vh] overflow-hidden rounded-[32px] shadow-2xl flex flex-col"
          >
            <div className="p-6 border-b border-bdr flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gold/10 rounded-full flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-gold" />
                </div>
                <div>
                  <h3 className="text-[20px] font-serif font-bold text-ink">
                    Paradigm: <span className="text-gold italic">{lemma}</span>
                  </h3>
                  <p className="text-[10px] text-muted uppercase tracking-widest font-bold">
                    Morphological Table
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 hover:bg-parch3 rounded-full transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-8 prose prose-slate max-w-none prose-sm prose-p:text-ink2 prose-headings:text-ink prose-strong:text-blue">
              {isLoading ? (
                <div className="flex flex-col items-center justify-center py-20 text-muted gap-4">
                  <Loader2 className="w-8 h-8 animate-spin text-blue" />
                  <p className="font-serif italic animate-pulse">
                    Consulting the ancient scrolls...
                  </p>
                </div>
              ) : (
                <div className="markdown-body">
                   <ReactMarkdown remarkPlugins={[remarkGfm]}>{paradigm || ""}</ReactMarkdown>
                </div>
              )}
            </div>

            <div className="p-6 bg-parch3/30 border-t border-bdr text-[11px] text-muted italic text-center">
              Generated by PalæoGlossa AI • Scholarly verification recommended
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
